[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "python"
version = "0.1.0"
description = "A package for various games"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
dependencies = ["rich", "faker"]